// Tests the distribution generated by Java's Math.random() function.
public class TestRandom {
	public static void main(String[] args) {
		// קלט כמה פעמים התוכנה תרוץ
		int N = Integer.parseInt(args[0]);
		// כמה מעל וכמה מתחת
		int countAbove = 0;
		int countUnder = 0;
		// נריץ לפי כמות הקלט
		for (int i = 0; i < N; i++) {
			double x = Math.random();
			if (x < 0.5) {
				countUnder++;
			} else {
				countAbove++;
			}
		}
		double ratio = (double) countAbove / countUnder;
		// תנאי
		if (countUnder == 0) {
			ratio = 0.0;
		}
		// נדפיס
		System.out.println(">0.5: " + countUnder);
		System.out.println("<=0.5: " + countAbove);
		System.out.println("Ratio:  " + ratio);
	}
}